=== leodenault/Believe/config/nifty-styles-1.3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://nifty-gui.sourceforge.net/nifty-styles-1.3.xsd" targetNamespace="http://nifty-gui.sourceforge.net/nifty-styles-1.3.xsd" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="nifty-styles" type="niftyStylesType"></xs:element>

  <xs:element name="effect" type="effectsType"></xs:element>
  <xs:element name="singleEffectbase" type="singleEffectTypeBase"></xs:element>
  <xs:element name="onStartScreen" type="singleEffectType" substitutionGroup="singleEffectbase" />
  <xs:element name="onEndScreen" type="singleEffectType" substitutionGroup="singleEffectbase" />
  <xs:element name="onHover" type="singleEffectTypeOnHover" substitutionGroup="singleEffectbase" />
  <xs:element name="onStartHover" type="singleEffectType" substitutionGroup="singleEffectbase" />
  <xs:element name="onEndHover" type="singleEffectType" substitutionGroup="singleEffectbase" />
  <xs:element name="onClick" type="singleEffectType" substitutionGroup="singleEffectbase" />
  <xs:element name="onFocus" type="singleEffectType" substitutionGroup="singleEffectbase" />
  <xs:element name="onLostFocus" type="singleEffectType" substitutionGroup="singleEffectbase" />
  <xs:element name="onGetFocus" type="singleEffectType" substitutionGroup="singleEffectbase" />
  <xs:element name="onActive" type="singleEffectType" substitutionGroup="singleEffectbase" />
  <xs:element name="onCustom" type="singleEffectType" substitutionGroup="singleEffectbase" />
  <xs:element name="onShow" type="singleEffectType" substitutionGroup="singleEffectbase" />
  <xs:element name="onHide" type="singleEffectType" substitutionGroup="singleEffectbase" />
  <xs:element name="onEnabled" type="singleEffectType" substitutionGroup="singleEffectbase" />
  <xs:element name="onDisabled" type="singleEffectType" substitutionGroup="singleEffectbase" />

  <xs:complexType name="registerMouseCursorType">
    <xs:attribute name="id" type="xs:string" use="required" />
    <xs:attribute name="filename" type="xs:string" use="required" />
    <xs:attribute name="hotspotX" type="xs:string" use="optional" />
    <xs:attribute name="hotspotY" type="xs:string" use="optional" />
  </xs:complexType>

  <xs:simpleType name="colorType">
    <xs:restriction base="xs:string">
      <xs:pattern value="#[a-z,0-9]{8,8}"></xs:pattern>
      <xs:pattern value="#[a-z,0-9]{4,4}"></xs:pattern>
      <xs:minLength value="5"></xs:minLength>
      <xs:maxLength value="9"></xs:maxLength>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="layoutType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="vertical"></xs:enumeration>
      <xs:enumeration value="center"></xs:enumeration>
      <xs:enumeration value="absolute"></xs:enumeration>
      <xs:enumeration value="horizontal"></xs:enumeration>
      <xs:enumeration value="overlay"></xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="directionType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="top"></xs:enumeration>
      <xs:enumeration value="bottom"></xs:enumeration>
      <xs:enumeration value="left"></xs:enumeration>
      <xs:enumeration value="right"></xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="alignType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="left"></xs:enumeration>
      <xs:enumeration value="center"></xs:enumeration>
      <xs:enumeration value="right"></xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="widthType">
    <xs:restriction base="xs:string"></xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="heightType">
    <xs:restriction base="xs:string"></xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="valignType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="top"></xs:enumeration>
      <xs:enumeration value="center"></xs:enumeration>
      <xs:enumeration value="bottom"></xs:enumeration>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="useStylesType">
    <xs:attribute name="filename" type="xs:string" use="required" />
  </xs:complexType>

  <xs:complexType name="attributesType">
    <xs:attribute name="height" type="xs:string" />
    <xs:attribute name="width" type="xs:string" />
    <xs:attribute name="x" type="xs:string" />
    <xs:attribute name="y" type="xs:string" />
    <xs:attribute name="align" type="xs:string" />
    <xs:attribute name="valign" type="xs:string" />
    <xs:attribute name="paddingLeft" type="xs:string" />
    <xs:attribute name="paddingRight" type="xs:string" />
    <xs:attribute name="paddingTop" type="xs:string" />
    <xs:attribute name="paddingBottom" type="xs:string" />
    <xs:attribute name="padding" type="xs:string" />
    <xs:attribute name="marginLeft" type="xs:string" />
    <xs:attribute name="marginRight" type="xs:string" />
    <xs:attribute name="marginTop" type="xs:string" />
    <xs:attribute name="marginBottom" type="xs:string" />
    <xs:attribute name="margin" type="xs:string" />
    <xs:attribute name="childClip" type="xs:string" />
    <xs:attribute name="visible" type="xs:string" />
    <xs:attribute name="visibleToMouse" type="xs:string" />
    <xs:attribute name="childLayout" type="xs:string" />
    <xs:attribute name="focusable" type="xs:string" />
    <xs:attribute name="backgroundImage" type="xs:string" />
    <xs:attribute name="backgroundColor" type="xs:string" />
    <xs:attribute name="color" type="xs:string" />
    <xs:attribute name="controller" type="xs:string" />
    <xs:attribute name="inputMapping" type="xs:string" />
    <xs:attribute name="textHAlign" type="xs:string" />
    <xs:attribute name="font" type="xs:string" />
    <xs:attribute name="filename" type="xs:string" />
    <xs:attribute name="wrap" type="xs:boolean" />
    <xs:attribute name="imageMode" type="xs:string" />
    <xs:attribute name="renderOrder" type="xs:int" />
    <xs:anyAttribute namespace="##any" processContents="skip" />
  </xs:complexType>

  <xs:simpleType name="onClickType">
    <xs:restriction base="xs:string" />
  </xs:simpleType>

  <xs:complexType name="interactType">
	<xs:attribute name="onClick" type="onClickType" />
    <xs:attribute name="onRelease" type="onClickType" />
    <xs:attribute name="onClickRepeat" type="onClickType" />
    <xs:attribute name="onClickMouseMove" type="onClickType" />

    <xs:attribute name="onPrimaryClick" type="onClickType" />
    <xs:attribute name="onPrimaryRelease" type="onClickType" />
    <xs:attribute name="onPrimaryClickRepeat" type="onClickType" />
    <xs:attribute name="onPrimaryClickMouseMove" type="onClickType" />

    <xs:attribute name="onSecondaryClick" type="onClickType" />
    <xs:attribute name="onSecondaryRelease" type="onClickType" />
    <xs:attribute name="onSecondaryClickRepeat" type="onClickType" />
    <xs:attribute name="onSecondaryClickMouseMove" type="onClickType" />

    <xs:attribute name="onTertiaryClick" type="onClickType" />
    <xs:attribute name="onTertiaryRelease" type="onClickType" />
    <xs:attribute name="onTertiaryClickRepeat" type="onClickType" />
    <xs:attribute name="onTertiaryClickMouseMove" type="onClickType" />

    <xs:attribute name="onMouseOver" type="onClickType" />
    <xs:attribute name="onClickAlternateKey" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="effectValueType">
    <xs:attribute name="time" type="xs:string"/>
    <xs:attribute name="value" type="xs:string"/>
    <xs:attribute name="offset" type="xs:string"/>
    <xs:attribute name="color" type="colorType"/>
  </xs:complexType>

  <xs:complexType name="singleEffectTypeBase">
    <xs:sequence>
      <xs:element name="value" type="effectValueType" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" />
    <xs:attribute name="startDelay" type="xs:string" />
    <xs:attribute name="length" type="xs:string" />
    <xs:attribute name="oneShot" type="xs:boolean" />
    <xs:attribute name="timeType" type="xs:string" />
    <xs:attribute name="factor" type="xs:string" />
    <xs:attribute name="inherit" type="xs:boolean" />
    <xs:attribute name="post" type="xs:boolean" />
    <xs:attribute name="alternateEnable" type="xs:string" />
    <xs:attribute name="alternateDisable" type="xs:string" />
    <xs:attribute name="onStartEffect" type="onClickType" />
    <xs:attribute name="onEndEffect" type="onClickType" />
    <xs:anyAttribute namespace="##any" processContents="skip" />
  </xs:complexType>

  <xs:complexType name="singleEffectType">
    <xs:complexContent>
      <xs:extension base="singleEffectTypeBase"></xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="singleEffectTypeOnHover">
    <xs:complexContent>
      <xs:extension base="singleEffectType">
        <xs:sequence>
          <xs:element name="hover" type="onHoverType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="onHoverType">
    <xs:attribute name="hoverFalloffType" type="xs:string" />
    <xs:attribute name="hoverFalloffConstraint" type="xs:string" />
    <xs:attribute name="hoverWidth" type="xs:string" />
    <xs:attribute name="hoverHeight" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="singleEffectTypeHover">
    <xs:attribute name="width" type="widthType" />
    <xs:attribute name="height" type="heightType" />
  </xs:complexType>

  <xs:complexType name="effectsType">
    <xs:sequence>
      <xs:element ref="singleEffectbase" minOccurs="0" maxOccurs="unbounded" />
	  </xs:sequence>
    <xs:attribute name="overlay" type="xs:boolean" />
  </xs:complexType>

  <xs:complexType name="styleType">
    <xs:sequence>
      <xs:element name="attributes" type="attributesType" maxOccurs="unbounded" minOccurs="0" />
      <xs:element name="interact" type="interactType" maxOccurs="unbounded" minOccurs="0" />
      <xs:element name="effect" type="effectsType" maxOccurs="unbounded" minOccurs="0" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" />
    <xs:attribute name="base" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="niftyStylesType">
    <xs:sequence>
      <xs:element name="registerMouseCursor" type="registerMouseCursorType" maxOccurs="unbounded" minOccurs="0" />
      <xs:element name="useStyles" type="useStylesType" maxOccurs="unbounded" minOccurs="0" />
      <xs:element name="style" type="styleType" maxOccurs="unbounded" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== leodenault/Believe/src/musicGame/gui/MenuSelectionStyle.xml
<?xml version="1.0" encoding="UTF-8"?>
<nifty-styles
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../../config/nifty-styles-1.3.xsd">
	
	<style id="menuSelection-border">
		<attributes backgroundColor="#cf0498" childLayout="center" width="500px" height="100px" padding="5px"/>
	</style>
	<style id="menuSelection-active-border">
		<attributes backgroundColor="#ffffff" childLayout="center" width="500px" height="100px" padding="5px"/>
	</style>
	<style id="menuSelection-background">
		<attributes backgroundColor="#0cffb2" childLayout="center" width="100%" height="100%"/>
	</style>
	<style id="menuSelection-active-background">
		<attributes backgroundColor="#ff0000" childLayout="center" width="100%" height="100%"/>
	</style>
	<style id="menuSelection-text">
		<attributes color="#cf0498" font="aurulent-sans-16.fnt"/>
	</style>
	<style id="menuSelection-active-text">
		<attributes color="#ffffff" font="aurulent-sans-16.fnt"/>
	</style>
</nifty-styles>
